
[site]
url = "https://rustmagazine.org"
name = "Rust Magazine"
description = "A publication dedicated to the Rust programming language."
edit_url = "https://github.com/rustmagazine/rustmagazine/edit/main"
menu = [
    { name = "About", url = "/about" },
    { name = "GitHub", url = "https://github.com/rustmagazine/rustmagazine" },
]
social_image = "/static/bg.jpeg"

[theme]
primary_color = "#f8e9b8"
secondary_color = "#faf8f3"
main_color = "#222c4b"
link_color = "#36a5ea"
background_image = "/static/bg.jpeg"
head_template = "templates/head.html"
footer_template = "templates/footer.html"
article_extend_template = "templates/article-extend.html"
default_cover = "/static/bg.jpeg"
default_avatar = "/static/avatar.png"

[markdown]
highlight_theme = "ayu-light"

[topics]
announcement = {}
interview = {}
game = { name = "Game development", description = "Topic of rust game development." }
pr-demystifying = { name = "PR Demystifying", description = "Topic of PR demystifying in Rust community." }
optimization = {}
async = {}
database = {}
business = { description = "Rust in Business" }
tutorial = {}

# Authors declare below
[authors]
rust-magazine = { name = "The Editorial Team", editor = true, bio = "The magazine editorial team" }
lcrossman = { name = "LCrossman", editor = true }
macko76 = { editor = true }
HandongZhang = { name = "Handong Zhang", editor = true }
pau1tuck = { name = "Paul Tuck", editor = true }
mfrw = { editor = true }
malagant = { name = "Michael Johann", editor = true, avatar = '/static/avatar/malagant.png' }
skyzh = { avatar = "/static/avatar/skyzh.jpeg" }

[authors.folyd]
editor = true
avatar = "/static/avatar/folyd.jpeg"
bio = """
The author of [Rust Search Extension](https://github.com/huhu/rust-search-extension) and [zine](https://github.com/zineland/zine).

- [GitHub](https://github.com/folyd)
- [Blog](https://folyd.com)
"""

[authors.yukang]
bio = """
- [GitHub](https://github.com/chenyukang)
- [Blog](https://catcoding.me)
"""

[authors.weihanglo]
name = "Weihang Lo"
avatar = "/static/avatar/weihanglo.png"

[authors.shijicheng]
name = "Jicheng Shi"

[authors.waynexia]
name = "Xia Ruihang"
bio = """
Working on [GreptimeDB](https://github.com/greptimeteam/greptimedb)

- [GitHub](https://github.com/waynexia)
- [Blog](https://blog.waynest.com)
"""

[authors.greptime-team]
name = "Greptime Team"
bio = """
Greptime is founded in April 2022 with two main offerings: [GreptimeDB](https://github.com/greptimeteam/greptimedb) and Greptime Cloud. 
- Greptime DB is an open-source, cloud-native time series database with powerful analytical features; 
- Greptime Cloud is a SaaS solution built on GreptimeDB. 

We are passionate about helping users find real-time values from their time series data with our tools.

- [GitHub](https://github.com/greptimeteam)
- [Website](https://greptime.com)
"""

[authors.xxchan]
name = "xxchan"
avatar = "/static/avatar/xxchan.png"
bio = """
- [GitHub](https://github.com/xxchan)
- [Blog](https://xxchan.github.io)
"""
