
[site]
url = "https://rustmagazine.github.io"
name = "Rust Magazine"
description = "A publication dedicated to the Rust programming language."
edit_url = "https://github.com/rustmagazine/rustmagazine.github.io/edit/main"
menu = [
    { name = "About", url = "/about" },
    { name = "GitHub", url = "https://github.com/rustmagazine/rustmagazine.github.io" },
]
social_image = "/static/bg.jpeg"

[authors]
rust-magazine = { name = "The Editor Team", editor = true, bio = "The magazine editor team" }
folyd = { editor = true, bio = """
The author of [Rust Search Extension](https://github.com/huhu/rust-search-extension) and [zine](https://github.com/zineland/zine).

- [Github](https://github.com/folyd)
- [Blog](https://folyd.com)
""" }
lcrossman = { name = "LCrossman", editor = true }
macko76 = { editor = true }

[theme]
primary_color = "#f8e9b8"
secondary_color = "#faf8f3"
main_color = "#222c4b"
link_color = "#36a5ea"
background_image = "/static/bg.jpeg"
head_template = "templates/head.html"
footer_template = "templates/footer.html"
article_extend_template = "templates/article-extend.html"
default_cover = "/static/bg.jpeg"
default_avatar = "/static/avatar.png"

[markdown]
highlight_theme = "ayu-light"

[topics]
announcement = {}
game = { name = "Game development", description = "Topic of rust game development." }
