slug = "issue-4"
number = 4
title = "Issue 4"
cover = "/static/ferris/4.jpeg"
pub_date = "2023-06-05"
publish = true

[[article]]
file = "show.md"
title = "Show Magazine #1"
author = "rust-magazine"
topic = ["show-magazine"]
pub_date = "2023-05-26"
publish = true
featured = true

[[article]]
file = "jhpratt.md"
title = "Interview with @jhpratt"
author = ["folyd", "jhpratt"]
topic = ["interview"]
pub_date = "2023-05-27"
publish = true
featured = true

[[article]]
file = "a-brief-discussion-on-invariants-in-rust.md"
title = "A Brief Discussion on Invariants in Rust: Essential Properties to Uphold"
author = ["TOETOE55"]
topic = ["unsafe-rust"]
pub_date = "2023-08-15"
publish = true
featured = true
i18n.zh = { file = "a-brief-discussion-on-invariants-in-rust-zh.md", title = "稍微聊聊Rust中的Invariant —— 那些必须保持的性质"}