slug = "issue-4"
number = 4
title = "Issue 4"
cover = "/static/ferris/4.jpeg"
default_cover = "/static/ferris/4.jpeg"
pub_date = "2023-06-05"
publish = false

[[article]]
file = "show.md"
title = "Show Magazine #1"
author = "rust-magazine"
topic = ["show-magazine"]
pub_date = "2023-05-26"
publish = true
featured = true