slug = "issue-4"
number = 4
title = "Issue 4"
cover = "/static/ferris/4.jpeg"
pub_date = "2023-06-05"
publish = true

[[article]]
file = "show.md"
title = "Show Magazine #1"
author = "rust-magazine"
topic = ["show-magazine"]
pub_date = "2023-05-26"
publish = true
featured = true

[[article]]
file = "jhpratt.md"
title = "Interview with @jhpratt"
author = ["folyd", "jhpratt"]
topic = ["interview"]
pub_date = "2023-05-27"
publish = true
featured = true

[[article]]
file = "a-brief-discussion-on-invariants-in-rust.md"
title = "A Brief Discussion on Invariants in Rust: Essential Properties to Uphold"
author = ["TOETOE55"]
topic = ["unsafe-rust"]
pub_date = "2023-08-15"
publish = true
featured = true
i18n.zh = { file = "a-brief-discussion-on-invariants-in-rust-zh.md", title = "稍微聊聊 Rust 中的 Invariant —— 那些必须保持的性质" }

[[article]]
file = "how-tokio-schedule-tasks.md"
title = "How Tokio schedule tasks: A hard Lesson learnt"
author = ["jiacai2050"]
topic = ["tokio", "async"]
pub_date = "2023-08-21"
publish = true
featured = true
i18n.zh = { file = "how-tokio-schedule-tasks-zh.md", title = "Tokio 任务调度原理分析" }