slug = "i"
number = 1
title = "Issue 1"

[[article]]
path = "/announcing"
file = "announcing.md"
title = "Announcing Rust Magazine"
author = "rust-magazine"
topic = ["annoucement"]
pub_date = "2022-12-10"
publish = true
featured = true
i18n.zh = { path = "/announcing-zh", file = "announcing-zh.md", title = "宣布 Rust 杂志", author = ["folyd", "rust-magazine"] }
