slug = "issue-1"
number = 1
title = "Issue 1"
cover = "/static/ferris/1.jpeg"
pub_date = "2023-02-06"
publish = true

[[article]]
path = "/announcing"
file = "announcing.md"
title = "Announcing Rust Magazine"
author = "rust-magazine"
topic = ["announcement"]
pub_date = "2022-12-10"
publish = true
featured = true
i18n.zh = { path = "/announcing-zh", file = "announcing-zh.md", title = "宣布 Rust 杂志" }

[[article]]
file = "vecdeque-resize-optimization.md"
title = "VecDeque::resize() optimization"
author = "folyd"
topic = ["pr-demystifying", "optimization"]
pub_date = "2022-12-24"
publish = true
featured = true

[[article]]
file = "minilsm.md"
title = "MiniLSM: A Tutorial of Building Storage Engine in a Week using Rust"
author = "skyzh"
topic = ["tutorial"]
pub_date = "2022-12-30"
publish = true
featured = true


[[article]]
file = "hidden-control-flow.md"
title = "The Hidden Control Flow — Some Insights on an Async Cancellation Problem in Rust"
author = ["waynexia", "greptime-team"]
topic = ["async", "database"]
pub_date = "2023-01-12"
publish = true
featured = true
canonical = "https://greptime.com/blogs/2023-01-12-hidden-control-flow.html"
i18n.zh = { file = "hidden-control-flow-zh.md", title = "看不见的控制流 — Rust 异步取消问题的几点思考"}

[[article]]
file = "contribute-to-rustc.md"
title = "How I contribute to Rust Compiler"
author = "yukang"
topic = ["tutorial"]
pub_date = "2023-01-29"
publish = true
featured = true

[[article]]
file = "weihanglo.md"
title = "Interview with Weihang Lo"
author = ["folyd", "weihanglo"]
topic = ["interview"]
pub_date = "2023-01-30"
publish = true
featured = true

[[article]]
file = "rust-for-linux-brief-introduction.md"
title = "Rust for Linux Brief Introduction"
author = "shijicheng"
topic = ["tutorial"]
pub_date = "2023-01-30"
publish = true
featured = true

[[article]]
file = "2022-review-the-adoption-of-rust-in-business.md"
title = "2022 Review | The adoption of Rust in Business"
author = "HandongZhang"
topic = ["business"]
pub_date = "2023-01-31"
publish = true
featured = true
i18n.zh = {file = "2022-review-the-adoption-of-rust-in-business-zh.md", title = "Rust 2022 全球商业化应用盘点", author = ["HandongZhang"] }
